shinyUI(navbarPage(theme = "bootstrap2.css", title="What's cooking?",
                   windowTitle="What's cooking?",
                   tabPanel("Guess The Cuisine",
                            fluidPage(
                              br(),
                              h1("Input your recipe and I guess the cuisine", align="left"),
                              br(),
                              column(5,
                                #br(),
                                #br(),
                                br(),
                                br(),
                                strong("Your recepie"),
                                br(),
                                br(),
                                br(),
                                br(),
                                tags$textarea(id="userInput", rows=12, style="width:80%;", ""),
                                #textInput("userInput", "Ingredients:", width= "200%"), 
                                #selectInput("model_type", "Type of model", c("Decission tree","Random forest"), selected = "Random forest"),
                                br(),br(),br(),
                                #h4("It must be:") , 
                                strong(h3(textOutput("output_prediction")))),
                              column(4,
                                br(),
                                br(),
                                h4("Common ingredients of this cuisine", align="center"),
                                br(),
                                plotOutput("wcloud")
                                )
                              )
                            ),
                   tabPanel("The Story",
                            fluidPage(
                              h1("What's \"What's cooking\"?", align="left"),
                              br(),
                              p("Whatscooking is the name of a machine learning competition on Kaggle (largest machine learning competition hosting portal). Hundreds of enthusiastic data scientists from all around the word (alone or in groups) are working on this challange."),
                              br(),
                              p("The goal is to make a model that predicts the category of a dish's cuisine given a list of its ingredients. In order to \"train\" the model a huge set of recipe is provided with the list of ingredients and the cuisine by Yummly. It's a US site so taste is little biased toward that direction."),
                              br(),
                              p("List of cuisines in the dataset:"),
                              tags$ul(  
                                tags$li("brazilian"),
                                tags$li("british"),
                                tags$li("cajun_creole"),
                                tags$li("chinese"),
                                tags$li("filipino"),
                                tags$li("french"),
                                tags$li("greek"),
                                tags$li("indian"),
                                tags$li("irish"),
                                tags$li("italian"),
                                tags$li("jamaican"),
                                tags$li("japanese"),
                                tags$li("korean"),
                                tags$li("mexican"),
                                tags$li("moroccan"),
                                tags$li("russian"),
                                tags$li("suthern_us"),
                                tags$li("spanish"),
                                tags$li("thai"),
                                tags$li("vietnamese") )
                            )
                          )              
              )
)